### ISSUE TITLE
When the DDI file is inaccessible, display an error message

### ISSUE THREAD

**Issue by jggautier** [scholarsportal/Dataverse-Data-Explorer#15]
Hi!

I'm trying to help a Harvard Dataverse user figure out why Data Explorer won't open a tabular file. When you try to "explore" the tabular file in the data at https://doi.org/10.7910/DVN/GDF6Z0, Data Explorer just hangs. Please let me know if this isn't the right place to ask for help or report this issue.

We thought it might have something to do with the large file sizes (bytes), or number of observations or variables. So I was planning to ask if you're aware of large file performance issues that we might be able to mitigate. But I've been testing with other ingested files and the number of bytes, observations and variables don't always seem to prevent Data Explorer from opening ingested files.

**Comment by kevinworthington** [comment]
This is probably as good a place as any to report such issues.

The problem in this cause seems to be due to the inaccessible DDI file at https://dataverse.harvard.edu/api/access/datafile/3123547/metadata/ddi.

I think it would be helpful to show an error message for instances like this but I haven't come across it until now.

**Comment by jggautier** [comment]
Thanks @kevinworthington for pointing out the variable metadata is inaccessible.

**Comment by kaitlinnewson** [comment]
Closing this as we're not updating this version of the Data Explorer, and moving over to: https://github.com/scholarsportal/dataverse-data-explorer-v2/issues/8
